In [88]:
import pandas as pd
import numpy as np
import os
import ast

In [89]:
# Folder path containing the CSV files
folder_path = r"C:\Users\User\Documents\ProAg_2023_CC\ProAg_2023_InSeason\CIs_dataframes"
# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]
target_file = "ProAg's AR no duplictes.csv"

# Check if target_file is in the list
if target_file in csv_files:
    # Remove target_file from its current position
    csv_files.remove(target_file)
    # Insert target_file at the beginning of the list
    csv_files.insert(0, target_file)
print(csv_files)

["ProAg's AR no duplictes.csv", 'crops_acres_df_20230501_forecast.csv', 'crops_acres_df_20230529.csv', 'crops_acres_df_20230612.csv', 'crops_acres_df_20230619.csv', 'crops_acres_df_20230627.csv', 'crops_acres_df_20230704.csv', 'crops_acres_df_20230711.csv', 'crops_acres_df_20230725.csv', 'crops_acres_df_20230808_v2.csv', 'crops_acres_df_20230822.csv']

In [90]:
# Create an empty DataFrame
result_df = pd.DataFrame()
result = []
names = []
# Process each CSV file
for csv_file in csv_files:
    file_path = os.path.join(folder_path, csv_file)
    df = pd.read_csv(file_path)
    df_name = csv_file[:-4]
    print(df_name)
    if df_name == "crops_acres_df_20230501_forecast":
        continue
    if df_name == "ProAg's AR no duplictes":
        # Remove duplicates based on specific columns
        df = df.drop_duplicates(subset=df.columns[0])
        cluid_values = df['CommonLandUnitId'].tolist()
        cropid_values = df['CommodityName'].tolist()
        print(len(cropid_values))
        print(len(cluid_values))
        rng = range(1, len(cropid_values)+1)
        print(rng)
        name = "Proag"
        ml_model_values = [(name, i) for i in rng]
        print(len(ml_model_values))
        replace_dict = {'Corn': '41', 'Cotton': '21', 'Wheat': '11', 'Soybeans': '81', 'Other': '101', 'Non Ag': '102'}
        #print(df)

        df = df.replace(replace_dict)
        #print(df)
    else:
        # filter out the forcast clus
        #df = df.loc[df['ml_model_code'] != 'f']
        # Extract cluid and cropid columns
        cluid_values = df['clu_id'].tolist()
        cropid_values = [eval(crop_dict)[0]['crop_code'] for crop_dict in df['crop_identification']]
        ml_model_values = df['ml_model_code'].tolist()
    if df_name not in names:
        names.append(df_name)
    df_name = pd.DataFrame(columns=['cluid', 'crop_code'])
    # Add cluid and crop_code values to the result DataFrame
    df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)
    clus_amount_last_CI = df_name.shape[0]
    result.append(df_name)
    print(df_name)
    print(df_name.info())
result

ProAg's AR no duplictes
154404
154404
range(1, 154405)
154404

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                       cluid crop_code         ml_model
0       000043F8-7B73-418C-8258-889DD97EDFAB      Corn       (Proag, 1)
1       00009398-6884-4F9D-AF20-9F6997D30B68  Soybeans       (Proag, 2)
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de      Corn       (Proag, 3)
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB    Cotton       (Proag, 4)
4       0002DC5F-9F69-404F-9353-862F373844C0  Soybeans       (Proag, 5)
...                                      ...       ...              ...
154399  fffaf815-385d-448c-8157-c5ea94663d84      Corn  (Proag, 154400)
154400  fffc87d1-7c40-40e8-96f4-6d79959b9f42  Soybeans  (Proag, 154401)
154401  fffc9a36-fc2c-4f0f-afd9-c7e9b427ac93      Corn  (Proag, 154402)
154402  fffc9d64-e0e5-4098-ad6c-43e6d0a898f0  Soybeans  (Proag, 154403)
154403  ffffc759-9129-4e43-9cf5-d0a251c6a5b7  Soybeans  (Proag, 154404)

[154404 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154404 entries, 0 to 154403
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      154404 non-null  object
 1   crop_code  154404 non-null  object
 2   ml_model   154404 non-null  object
dtypes: object(3)
memory usage: 3.5+ MB
None
crops_acres_df_20230501_forecast
crops_acres_df_20230529

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)
C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                     cluid crop_code ml_model
0     802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
1     E0DAB01B-634A-4E02-A9F0-655CB9CA7AE4        81       Y1
2     0D4CE56E-3819-4A07-8961-30CFD8D68D03        81       Y1
3     73BA7711-74EB-44F3-8F72-D988EF07B079       101       Y1
4     A60FE5CA-DCE3-4BA2-90E7-F4591344CA95        81       Y1
...                                    ...       ...      ...
1236  AAAE00F7-31C4-4FC2-A980-2EE95DE5FF64        41       Y1
1237  893C33AE-266B-4C21-860B-8BDA8F4B2207        81       Y1
1238  2FDB5A06-4BCF-441A-946E-3AB84142EC8F        81       Y1
1239  CA2903FF-4D81-47C6-99A1-8482527E2EEB        41       Y1
1240  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1

[1241 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cluid      1241 non-null   object
 1   crop_code  1241 non-null   object
 2   ml_model   1241 non-null   object
dtypes: object(3)
memory usage: 29.2+ KB
None
crops_acres_df_20230612
                                     cluid crop_code ml_model
0     802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
1     7B7E8228-8E39-4616-80F8-64B538773483        81       Y2
2     82617850-BBA9-4BA3-AE37-BC2A6C168A73        41       Y2
3     E0DAB01B-634A-4E02-A9F0-655CB9CA7AE4        81       Y1
4     1F080C14-E25A-40E4-A588-02DE8ED34C13        41       Y2
...                                    ...       ...      ...
6321  8F4F6DD7-10A5-4746-B83F-D6D95F599FCA       101       Y2
6322  F344C9A5-302C-407F-B0E0-DB2063D97DCE       101       Y2
6323  523177AF-2400-4F8D-8B4B-3EFC55C94E4F        81       Y2
6324  33DE0B1C-36D9-48F7-849F-0D6F8B2BAF50        81       Y2
6325  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1

[6326 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6326 entries, 0 to 6325
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cluid      6326 non-null   object
 1   crop_code  6326 non-null   object
 2   ml_model   6326 non-null   object
dtypes: object(3)
memory usage: 148.4+ KB
None
crops_acres_df_20230619

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                      cluid crop_code ml_model
0      0D45A6D4-5C0F-49C1-86FF-E0021962EEB0        41       Y3
1      ab16c8b0-d8eb-46f6-a3ca-95e5e93c59a4       101       Y3
2      802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
3      C1A08AE1-E0BF-492C-A6D6-D7E8EA1EFD78        11       Y3
4      3e8facae-7a63-4696-96b7-AD0b8df75f16        21       Y3
...                                     ...       ...      ...
12458  B6404D7C-4A6B-4CC4-914B-01467C7E1204        81       Y3
12459  CA439617-92B2-432E-9834-872C96CD38EE        81       Y3
12460  33DE0B1C-36D9-48F7-849F-0D6F8B2BAF50        81       Y2
12461  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1
12462  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3

[12463 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12463 entries, 0 to 12462
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cluid      12463 non-null  object
 1   crop_code  12463 non-null  object
 2   ml_model   12463 non-null  object
dtypes: object(3)
memory usage: 292.2+ KB
None
crops_acres_df_20230627

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                      cluid crop_code ml_model
0      e2748598-ac09-4153-8585-da59b545f1ef        81       Y4
1      2CC6B43E-3E5D-4283-9991-0C573E997B85        41       Y4
2      244244d7-004a-4aab-94ef-4cdb19e91745        41       Y4
3      0D45A6D4-5C0F-49C1-86FF-E0021962EEB0        41       Y3
4      FE90C4B9-CBEB-4D56-9ABF-C8BCA9AE8354        81       Y4
...                                     ...       ...      ...
22346  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1
22347  688E1BB0-FADA-479F-9D7F-02966C026DAF       101       Y4
22348  296EDFAF-2A52-4D91-88E4-A8823431630C        41       Y4
22349  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
22350  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4

[22351 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22351 entries, 0 to 22350
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cluid      22351 non-null  object
 1   crop_code  22351 non-null  object
 2   ml_model   22351 non-null  object
dtypes: object(3)
memory usage: 524.0+ KB
None
crops_acres_df_20230704

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                       cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81        f
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        81        f
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41        f
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        41        f
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y5
...                                      ...       ...      ...
113451  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
113452  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4
113453  7ACE9A78-A90F-4C35-A610-34D390CC411C        81        f
113454  54507aa1-1bbf-45c0-b5d6-78426115a89d        81        f
113455  5791C8FF-2E31-4C15-941A-465B781909BC        81        f

[113456 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113456 entries, 0 to 113455
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      113456 non-null  object
 1   crop_code  113456 non-null  object
 2   ml_model   113456 non-null  object
dtypes: object(3)
memory usage: 2.6+ MB
None
crops_acres_df_20230711

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                       cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81        f
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        11        f
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41        f
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        41        f
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y5
...                                      ...       ...      ...
115601  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
115602  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4
115603  7ACE9A78-A90F-4C35-A610-34D390CC411C        81       Y6
115604  54507aa1-1bbf-45c0-b5d6-78426115a89d        21        f
115605  5791C8FF-2E31-4C15-941A-465B781909BC        41        f

[115606 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115606 entries, 0 to 115605
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      115606 non-null  object
 1   crop_code  115606 non-null  object
 2   ml_model   115606 non-null  object
dtypes: object(3)
memory usage: 2.6+ MB
None
crops_acres_df_20230725

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                       cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81       Y7
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41        f
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41       Y7
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81        f
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y7
...                                      ...       ...      ...
115603  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y7
115604  6F7A3E71-17B0-4D49-910F-3398286568CD        41       Y7
115605  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       Y7
115606  54507aa1-1bbf-45c0-b5d6-78426115a89d        21        f
115607  5791C8FF-2E31-4C15-941A-465B781909BC        41        f

[115608 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115608 entries, 0 to 115607
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      115608 non-null  object
 1   crop_code  115608 non-null  object
 2   ml_model   115608 non-null  object
dtypes: object(3)
memory usage: 2.6+ MB
None
crops_acres_df_20230808_v2

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

                                       cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81       Y8
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41        f
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41       Y8
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81       B8
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y8
...                                      ...       ...      ...
115607  37788F5F-8A25-4C5A-97D3-DE1895D36CD1        81       B8
115608  6F7A3E71-17B0-4D49-910F-3398286568CD        41       Y8
115609  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       B8
115610  54507aa1-1bbf-45c0-b5d6-78426115a89d        21       Y8
115611  5791C8FF-2E31-4C15-941A-465B781909BC        41       Y8

[115612 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115612 entries, 0 to 115611
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      115612 non-null  object
 1   crop_code  115612 non-null  object
 2   ml_model   115612 non-null  object
dtypes: object(3)
memory usage: 2.6+ MB
None
crops_acres_df_20230822
                                       cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81      Y8a
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41       fa
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41      Y9a
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81       B8
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41      Y9a
...                                      ...       ...      ...
115605  37788F5F-8A25-4C5A-97D3-DE1895D36CD1        81       B8
115606  6F7A3E71-17B0-4D49-910F-3398286568CD        41      Y9a
115607  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       B8
115608  54507aa1-1bbf-45c0-b5d6-78426115a89d        21      Y9a
115609  5791C8FF-2E31-4C15-941A-465B781909BC        41      Y8a

[115610 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115610 entries, 0 to 115609
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cluid      115610 non-null  object
 1   crop_code  115610 non-null  object
 2   ml_model   115610 non-null  object
dtypes: object(3)
memory usage: 2.6+ MB
None

C:\Users\User\AppData\Local\Temp\ipykernel_45176\330333372.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_name = df_name.append(pd.DataFrame({'cluid': cluid_values, 'crop_code': cropid_values, 'ml_model': ml_model_values}), ignore_index=True)

[                                       cluid crop_code         ml_model
 0       000043F8-7B73-418C-8258-889DD97EDFAB      Corn       (Proag, 1)
 1       00009398-6884-4F9D-AF20-9F6997D30B68  Soybeans       (Proag, 2)
 2       0000dfbe-5904-48a9-9b02-c9de79dfa4de      Corn       (Proag, 3)
 3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB    Cotton       (Proag, 4)
 4       0002DC5F-9F69-404F-9353-862F373844C0  Soybeans       (Proag, 5)
 ...                                      ...       ...              ...
 154399  fffaf815-385d-448c-8157-c5ea94663d84      Corn  (Proag, 154400)
 154400  fffc87d1-7c40-40e8-96f4-6d79959b9f42  Soybeans  (Proag, 154401)
 154401  fffc9a36-fc2c-4f0f-afd9-c7e9b427ac93      Corn  (Proag, 154402)
 154402  fffc9d64-e0e5-4098-ad6c-43e6d0a898f0  Soybeans  (Proag, 154403)
 154403  ffffc759-9129-4e43-9cf5-d0a251c6a5b7  Soybeans  (Proag, 154404)

 [154404 rows x 3 columns],
                                      cluid crop_code ml_model
 0     802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
 1     E0DAB01B-634A-4E02-A9F0-655CB9CA7AE4        81       Y1
 2     0D4CE56E-3819-4A07-8961-30CFD8D68D03        81       Y1
 3     73BA7711-74EB-44F3-8F72-D988EF07B079       101       Y1
 4     A60FE5CA-DCE3-4BA2-90E7-F4591344CA95        81       Y1
 ...                                    ...       ...      ...
 1236  AAAE00F7-31C4-4FC2-A980-2EE95DE5FF64        41       Y1
 1237  893C33AE-266B-4C21-860B-8BDA8F4B2207        81       Y1
 1238  2FDB5A06-4BCF-441A-946E-3AB84142EC8F        81       Y1
 1239  CA2903FF-4D81-47C6-99A1-8482527E2EEB        41       Y1
 1240  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1

 [1241 rows x 3 columns],
                                      cluid crop_code ml_model
 0     802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
 1     7B7E8228-8E39-4616-80F8-64B538773483        81       Y2
 2     82617850-BBA9-4BA3-AE37-BC2A6C168A73        41       Y2
 3     E0DAB01B-634A-4E02-A9F0-655CB9CA7AE4        81       Y1
 4     1F080C14-E25A-40E4-A588-02DE8ED34C13        41       Y2
 ...                                    ...       ...      ...
 6321  8F4F6DD7-10A5-4746-B83F-D6D95F599FCA       101       Y2
 6322  F344C9A5-302C-407F-B0E0-DB2063D97DCE       101       Y2
 6323  523177AF-2400-4F8D-8B4B-3EFC55C94E4F        81       Y2
 6324  33DE0B1C-36D9-48F7-849F-0D6F8B2BAF50        81       Y2
 6325  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1

 [6326 rows x 3 columns],
                                       cluid crop_code ml_model
 0      0D45A6D4-5C0F-49C1-86FF-E0021962EEB0        41       Y3
 1      ab16c8b0-d8eb-46f6-a3ca-95e5e93c59a4       101       Y3
 2      802952DF-CC35-4CA5-A29F-E71B8A77465F        81       Y1
 3      C1A08AE1-E0BF-492C-A6D6-D7E8EA1EFD78        11       Y3
 4      3e8facae-7a63-4696-96b7-AD0b8df75f16        21       Y3
 ...                                     ...       ...      ...
 12458  B6404D7C-4A6B-4CC4-914B-01467C7E1204        81       Y3
 12459  CA439617-92B2-432E-9834-872C96CD38EE        81       Y3
 12460  33DE0B1C-36D9-48F7-849F-0D6F8B2BAF50        81       Y2
 12461  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1
 12462  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3

 [12463 rows x 3 columns],
                                       cluid crop_code ml_model
 0      e2748598-ac09-4153-8585-da59b545f1ef        81       Y4
 1      2CC6B43E-3E5D-4283-9991-0C573E997B85        41       Y4
 2      244244d7-004a-4aab-94ef-4cdb19e91745        41       Y4
 3      0D45A6D4-5C0F-49C1-86FF-E0021962EEB0        41       Y3
 4      FE90C4B9-CBEB-4D56-9ABF-C8BCA9AE8354        81       Y4
 ...                                     ...       ...      ...
 22346  42d271c9-705a-40d9-8794-89bc98c0350f        81       Y1
 22347  688E1BB0-FADA-479F-9D7F-02966C026DAF       101       Y4
 22348  296EDFAF-2A52-4D91-88E4-A8823431630C        41       Y4
 22349  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
 22350  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4

 [22351 rows x 3 columns],
                                        cluid crop_code ml_model
 0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81        f
 1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        81        f
 2       A1596150-F2BA-437B-8C38-BAB392013FD7        41        f
 3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        41        f
 4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y5
 ...                                      ...       ...      ...
 113451  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
 113452  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4
 113453  7ACE9A78-A90F-4C35-A610-34D390CC411C        81        f
 113454  54507aa1-1bbf-45c0-b5d6-78426115a89d        81        f
 113455  5791C8FF-2E31-4C15-941A-465B781909BC        81        f

 [113456 rows x 3 columns],
                                        cluid crop_code ml_model
 0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81        f
 1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        11        f
 2       A1596150-F2BA-437B-8C38-BAB392013FD7        41        f
 3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        41        f
 4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y5
 ...                                      ...       ...      ...
 115601  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y3
 115602  6F7A3E71-17B0-4D49-910F-3398286568CD       101       Y4
 115603  7ACE9A78-A90F-4C35-A610-34D390CC411C        81       Y6
 115604  54507aa1-1bbf-45c0-b5d6-78426115a89d        21        f
 115605  5791C8FF-2E31-4C15-941A-465B781909BC        41        f

 [115606 rows x 3 columns],
                                        cluid crop_code ml_model
 0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81       Y7
 1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41        f
 2       A1596150-F2BA-437B-8C38-BAB392013FD7        41       Y7
 3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81        f
 4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y7
 ...                                      ...       ...      ...
 115603  37788F5F-8A25-4C5A-97D3-DE1895D36CD1       101       Y7
 115604  6F7A3E71-17B0-4D49-910F-3398286568CD        41       Y7
 115605  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       Y7
 115606  54507aa1-1bbf-45c0-b5d6-78426115a89d        21        f
 115607  5791C8FF-2E31-4C15-941A-465B781909BC        41        f

 [115608 rows x 3 columns],
                                        cluid crop_code ml_model
 0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81       Y8
 1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41        f
 2       A1596150-F2BA-437B-8C38-BAB392013FD7        41       Y8
 3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81       B8
 4       E7D7D229-E961-47AE-9E98-90213AC19D98        41       Y8
 ...                                      ...       ...      ...
 115607  37788F5F-8A25-4C5A-97D3-DE1895D36CD1        81       B8
 115608  6F7A3E71-17B0-4D49-910F-3398286568CD        41       Y8
 115609  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       B8
 115610  54507aa1-1bbf-45c0-b5d6-78426115a89d        21       Y8
 115611  5791C8FF-2E31-4C15-941A-465B781909BC        41       Y8

 [115612 rows x 3 columns],
                                        cluid crop_code ml_model
 0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81      Y8a
 1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41       fa
 2       A1596150-F2BA-437B-8C38-BAB392013FD7        41      Y9a
 3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81       B8
 4       E7D7D229-E961-47AE-9E98-90213AC19D98        41      Y9a
 ...                                      ...       ...      ...
 115605  37788F5F-8A25-4C5A-97D3-DE1895D36CD1        81       B8
 115606  6F7A3E71-17B0-4D49-910F-3398286568CD        41      Y9a
 115607  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       B8
 115608  54507aa1-1bbf-45c0-b5d6-78426115a89d        21      Y9a
 115609  5791C8FF-2E31-4C15-941A-465B781909BC        41      Y8a

 [115610 rows x 3 columns]]

In [91]:
# Create an empty DataFrame to store the aggregated results
result_df = pd.DataFrame()
models_df = pd.DataFrame()
# Iterate over each DataFrame and its corresponding column name
for df, column_name in zip(result, names):
    # Aggregate the crop values for each name
    aggregated_df = df.groupby('cluid')['crop_code'].agg(list).reset_index()
#     print(aggregated_df)
    aggregated_model_df = df.groupby('cluid')['ml_model'].agg(list).reset_index()
    # Rename the 'crop' column with the corresponding column name
    aggregated_df.rename(columns={'crop_code': column_name}, inplace=True)
    aggregated_model_df.rename(columns={'ml_model': column_name}, inplace=True)
    # Merge the aggregated results with the previous results
    if result_df.empty:
        result_df = aggregated_df
    else:
        result_df = result_df.merge(aggregated_df, on='cluid', how='outer')
    print(result_df)
    if models_df.empty:
        models_df = aggregated_model_df
    else:
        models_df = models_df.merge(aggregated_model_df, on='cluid', how='outer')
#     print(models_df)
replace_dict = {'41': 'Corn', '21': 'Cotton', '11': 'Wheat', '81': 'Soybeans', '101': 'Other', '102': 'Non Ag'}
# Fill NaN values with empty lists
result_df = result_df.fillna('')
for column in result_df.columns[1:]:
    result_df[column] = result_df[column].apply(lambda x: str(x)[1:-1])

# Print the resulting DataFrame
result_df = result_df.apply(lambda x: x.str.replace("'", ""))
result_df = result_df.replace(replace_dict)
# remove empty rows (because of the proag file)
result_df = result_df[result_df.iloc[:, 1:].apply(lambda x: x.ne('').any(), axis=1)]
result_df

                                       cluid ProAg's AR no duplictes
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
154399  fffaf815-385d-448c-8157-c5ea94663d84                  [Corn]
154400  fffc87d1-7c40-40e8-96f4-6d79959b9f42              [Soybeans]
154401  fffc9a36-fc2c-4f0f-afd9-c7e9b427ac93                  [Corn]
154402  fffc9d64-e0e5-4098-ad6c-43e6d0a898f0              [Soybeans]
154403  ffffc759-9129-4e43-9cf5-d0a251c6a5b7              [Soybeans]

[154404 rows x 2 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
154706  d2b977ca-dc7c-11d6-8ea4-00065b57b52a                     NaN
154707  d2b977ea-dc7c-11d6-8ea4-00065b57b52a                     NaN
154708  da646e5e-73f9-42c2-a828-6e4981a3ab0c                     NaN
154709  db5158c3-3219-40e6-bf57-0268d608c640                     NaN
154710  ec384fc1-c643-47ae-938b-dfeb7b58459d                     NaN

       crops_acres_df_20230529
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
...                        ...
154706                   [101]
154707                    [41]
154708                    [81]
154709                    [41]
154710                    [41]

[154711 rows x 3 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
155753  fcee8acf-c8dd-42f1-8569-d680dcd4569f                     NaN
155754  fd5e9298-5f3f-4818-8a2d-ad99347c389b                     NaN
155755  fd695011-fbb1-4635-b23c-1fcfdeab6e76                     NaN
155756  fddc7b03-cb90-467d-ac66-01c0301631f3                     NaN
155757  fe646fae-cba5-4104-8fb4-62b76ad098e5                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
155753                     NaN                    [21]
155754                     NaN                    [21]
155755                     NaN                    [81]
155756                     NaN                    [81]
155757                     NaN                    [81]

[155758 rows x 4 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
157335  fbd91ba4-bcb0-449d-a7e7-5d07a5746ebf                     NaN
157336  fc84fcc4-a483-4051-afe1-2688d317e74f                     NaN
157337  fe5ecb54-51b7-448b-9100-165c633166aa                     NaN
157338  ff384a69-c64e-4842-a7e0-ba4cc1398e04                     NaN
157339  ffc1abec-c998-11d6-8ea6-00065b903365                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612 crops_acres_df_20230619
0                          NaN                     NaN                     NaN
1                          NaN                     NaN                     NaN
2                          NaN                     NaN                     NaN
3                          NaN                     NaN                     NaN
4                          NaN                     NaN                     NaN
...                        ...                     ...                     ...
157335                     NaN                     NaN                    [81]
157336                     NaN                     NaN                    [81]
157337                     NaN                     NaN                   [101]
157338                     NaN                     NaN                   [101]
157339                     NaN                     NaN                    [81]

[157340 rows x 5 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
159222  fb7a000c-c133-4d0a-822c-6af3aebc0943                     NaN
159223  fc06fd7d-d7e3-419a-bb9b-74a6718dc5a1                     NaN
159224  fc566c6d-381c-4b63-9b99-4032761eb619                     NaN
159225  fd1a8187-162a-4369-86f0-2687831d2f12                     NaN
159226  fe5f6650-647c-4906-94de-b643ae7b0e4f                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
159222                     NaN                     NaN
159223                     NaN                     NaN
159224                     NaN                     NaN
159225                     NaN                     NaN
159226                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
159222                     NaN                    [81]
159223                     NaN                    [81]
159224                     NaN                   [101]
159225                     NaN                   [101]
159226                     NaN                    [41]

[159227 rows x 6 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
179903  ffd94f20-737b-4b6c-830c-fa2adaa924f2                     NaN
179904  ffe27495-0c73-415b-be1e-652f04c27dc7                     NaN
179905  fff0ccc0-9c05-4fb3-bf90-fc5811762349                     NaN
179906  fff539a4-729b-4c4a-8e18-064c2eadd266                     NaN
179907  fff5d91b-4092-4a6a-8d81-a56917d1fccb                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
179903                     NaN                     NaN
179904                     NaN                     NaN
179905                     NaN                     NaN
179906                     NaN                     NaN
179907                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627 crops_acres_df_20230704
0                          NaN                     NaN                    [41]
1                          NaN                     NaN                     NaN
2                          NaN                     NaN                     NaN
3                          NaN                     NaN                   [101]
4                          NaN                     NaN                    [41]
...                        ...                     ...                     ...
179903                     NaN                     NaN                    [81]
179904                     NaN                     NaN                   [101]
179905                     NaN                     NaN                    [41]
179906                     NaN                     NaN                    [81]
179907                     NaN                     NaN                   [101]

[179908 rows x 7 columns]

                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
180726  fc1da979-aaf6-49a1-bad3-2c87c1003c6f                     NaN
180727  fdb29af0-5f2c-448d-8cff-b062c019e18e                     NaN
180728  fdf50fb5-6467-4f3d-8e4e-52509ff41a88                     NaN
180729  ff1a7b5d-a436-448a-8162-87549b35f9d3                     NaN
180730  ff9cc52e-0b58-11d6-9fae-00b0d07bb233                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180726                     NaN                     NaN
180727                     NaN                     NaN
180728                     NaN                     NaN
180729                     NaN                     NaN
180730                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180726                     NaN                     NaN
180727                     NaN                     NaN
180728                     NaN                     NaN
180729                     NaN                     NaN
180730                     NaN                     NaN

       crops_acres_df_20230704 crops_acres_df_20230711
0                         [41]                    [41]
1                          NaN                     NaN
2                          NaN                     NaN
3                        [101]                    [81]
4                         [41]                    [81]
...                        ...                     ...
180726                     NaN                   [101]
180727                     NaN                    [21]
180728                     NaN                    [21]
180729                     NaN                    [21]
180730                     NaN                   [101]

[180731 rows x 8 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
180730  ff9cc52e-0b58-11d6-9fae-00b0d07bb233                     NaN
180731  08FAA086-B4CF-4738-8672-F3D951D01FB8                     NaN
180732  4679FF08-CC4C-4C13-8D4E-D73ABBC3885D                     NaN
180733  55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3                     NaN
180734  63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180730                     NaN                     NaN
180731                     NaN                     NaN
180732                     NaN                     NaN
180733                     NaN                     NaN
180734                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180730                     NaN                     NaN
180731                     NaN                     NaN
180732                     NaN                     NaN
180733                     NaN                     NaN
180734                     NaN                     NaN

       crops_acres_df_20230704 crops_acres_df_20230711 crops_acres_df_20230725
0                         [41]                    [41]                   [101]
1                          NaN                     NaN                     NaN
2                          NaN                     NaN                     NaN
3                        [101]                    [81]                    [21]
4                         [41]                    [81]                    [81]
...                        ...                     ...                     ...
180730                     NaN                   [101]                    [21]
180731                     NaN                     NaN                    [41]
180732                     NaN                     NaN                   [102]
180733                     NaN                     NaN                   [102]
180734                     NaN                     NaN                   [101]

[180735 rows x 9 columns]
                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
180733  55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3                     NaN
180734  63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C                     NaN
180735  52B817D4-793B-43CA-B432-40EF5EE8040D                     NaN
180736  8929d73b-739c-451b-9b6e-fe09ee5fa725                     NaN
180737  A591B261-0E75-40B6-A8A6-07E56E282CF3                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230704 crops_acres_df_20230711  \
0                         [41]                    [41]
1                          NaN                     NaN
2                          NaN                     NaN
3                        [101]                    [81]
4                         [41]                    [81]
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230725 crops_acres_df_20230808_v2
0                        [101]                       [41]
1                          NaN                        NaN
2                          NaN                        NaN
3                         [21]                       [21]
4                         [81]                       [81]
...                        ...                        ...
180733                   [102]                        NaN
180734                   [101]                       [81]
180735                     NaN                       [81]
180736                     NaN                       [41]
180737                     NaN                       [81]

[180738 rows x 10 columns]

                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                  [Corn]
1       00009398-6884-4F9D-AF20-9F6997D30B68              [Soybeans]
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                  [Corn]
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                [Cotton]
4       0002DC5F-9F69-404F-9353-862F373844C0              [Soybeans]
...                                      ...                     ...
180733  55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3                     NaN
180734  63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C                     NaN
180735  52B817D4-793B-43CA-B432-40EF5EE8040D                     NaN
180736  8929d73b-739c-451b-9b6e-fe09ee5fa725                     NaN
180737  A591B261-0E75-40B6-A8A6-07E56E282CF3                     NaN

       crops_acres_df_20230529 crops_acres_df_20230612  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230619 crops_acres_df_20230627  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230704 crops_acres_df_20230711  \
0                         [41]                    [41]
1                          NaN                     NaN
2                          NaN                     NaN
3                        [101]                    [81]
4                         [41]                    [81]
...                        ...                     ...
180733                     NaN                     NaN
180734                     NaN                     NaN
180735                     NaN                     NaN
180736                     NaN                     NaN
180737                     NaN                     NaN

       crops_acres_df_20230725 crops_acres_df_20230808_v2  \
0                        [101]                       [41]
1                          NaN                        NaN
2                          NaN                        NaN
3                         [21]                       [21]
4                         [81]                       [81]
...                        ...                        ...
180733                   [102]                        NaN
180734                   [101]                       [81]
180735                     NaN                       [81]
180736                     NaN                       [41]
180737                     NaN                       [81]

       crops_acres_df_20230822
0                         [41]
1                          NaN
2                          NaN
3                         [21]
4                         [81]
...                        ...
180733                     NaN
180734                    [81]
180735                     NaN
180736                    [41]
180737                     NaN

[180738 rows x 11 columns]

,cluid,ProAg's AR no duplictes,crops_acres_df_20230529,crops_acres_df_20230612,crops_acres_df_20230619,crops_acres_df_20230627,crops_acres_df_20230704,crops_acres_df_20230711,crops_acres_df_20230725,crops_acres_df_20230808_v2,crops_acres_df_20230822
0,000043F8-7B73-418C-8258-889DD97EDFAB,Corn,,,,,Corn,Corn,Other,Corn,Corn
1,00009398-6884-4F9D-AF20-9F6997D30B68,Soybeans,,,,,,,,,
2,0000dfbe-5904-48a9-9b02-c9de79dfa4de,Corn,,,,,,,,,
3,00012A0C-34A8-4021-BF0B-7645FB6DF7BB,Cotton,,,,,Other,Soybeans,Cotton,Cotton,Cotton
4,0002DC5F-9F69-404F-9353-862F373844C0,Soybeans,,,,,Corn,Soybeans,Soybeans,Soybeans,Soybeans
...,...,...,...,...,...,...,...,...,...,...,...
180733,55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3,,,,,,,,Non Ag,,
180734,63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C,,,,,,,,Other,Soybeans,Soybeans
180735,52B817D4-793B-43CA-B432-40EF5EE8040D,,,,,,,,,Soybeans,
180736,8929d73b-739c-451b-9b6e-fe09ee5fa725,,,,,,,,,Corn,Corn
180737,A591B261-0E75-40B6-A8A6-07E56E282CF3,,,,,,,,,Soybeans,

In [92]:
# Count the number of non-empty values in each row for the specific columns
# Get the specific columns from the second column to the end
specific_columns = result_df.columns[2:]
result_df['CIs_value_count'] = result_df[specific_columns].apply(lambda x: x[x != ''].count(), axis=1)


# Create a new column with default value 'Yes'
result_df['ALL_CIs_Match_forecast'] = 'Yes'
result_df['Last_CI_value_Match_forecast'] = 'Yes'

print(result_df.info())
# Iterate over each row in the DataFrame
for index, row in result_df.iterrows():
    # Get the value in the second column
    match_value = row[1]
    # Check if all values from the second column onwards match the value in the second column
    #if not all(row[2:-3] == match_value) and match_value != "":
    if match_value != "" and not all(x == match_value for x in row[2:-3] if x != ""):
        # If any value doesn't match, update the 'Match_All' column to 'No'
        result_df.at[index, 'ALL_CIs_Match_forecast'] = 'No'

    # Update if match_value is empty
    if match_value == "":
        result_df.at[index, 'ALL_CIs_Match_forecast'] = 'No'
        result_df.at[index, 'Last_CI_value_Match_forecast'] = 'No'
    else:
        if not row[-4] == match_value:
            result_df.at[index, 'Last_CI_value_Match_forecast'] = 'No'


# Count the occurrences of 'Yes' in the 'Match_All' column
all_yes_count = (result_df['ALL_CIs_Match_forecast'] == 'Yes').sum()
last_yes_count = (result_df['Last_CI_value_Match_forecast'] == 'Yes').sum()
print(all_yes_count)
print(last_yes_count)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180738 entries, 0 to 180737
Data columns (total 14 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   cluid                         180738 non-null  object
 1   ProAg's AR no duplictes       180738 non-null  object
 2   crops_acres_df_20230529       180738 non-null  object
 3   crops_acres_df_20230612       180738 non-null  object
 4   crops_acres_df_20230619       180738 non-null  object
 5   crops_acres_df_20230627       180738 non-null  object
 6   crops_acres_df_20230704       180738 non-null  object
 7   crops_acres_df_20230711       180738 non-null  object
 8   crops_acres_df_20230725       180738 non-null  object
 9   crops_acres_df_20230808_v2    180738 non-null  object
 10  crops_acres_df_20230822       180738 non-null  object
 11  CIs_value_count               180738 non-null  int64
 12  ALL_CIs_Match_forecast        180738 non-null  object
 13  Last_CI_value_Match_forecast  180738 non-null  object
dtypes: int64(1), object(13)
memory usage: 20.7+ MB
None
102137
71230

In [93]:
# Calculate the percentage relative to the number of rows in the first column
percent_value = (all_yes_count / result_df.shape[0]) * 100
result_df['ALL_CIs_Match_percent'] = ''
result_df.at[0, 'ALL_CIs_Match_percent'] = percent_value
# Calculate the percentage relative to the number of rows in the first column
last_percent_value = (last_yes_count / result_df.shape[0]) * 100
result_df['Last_CI_value_Match_forecast_percent'] = ''
result_df.at[0, 'Last_CI_value_Match_forecast_percent'] = last_percent_value


subset_columns = result_df.columns[2:-5]

# Calculate the most frequent value for each row
most_frequent_values2 = result_df[subset_columns].apply(
    lambda x: x.value_counts().idxmax() if (x.nunique() > 1 and x.value_counts().idxmax() not in ["", float("nan")])
    else x.value_counts().index[1] if len(x.value_counts()) > 1
    else x.value_counts().idxmax() if len(x.value_counts()) == 1 and x.value_counts().idxmax() not in ["", float("nan")]
    else None,
    axis=1
)

In [94]:
insert_position_All_Same_Value = len(result_df.columns) - 4
# if all values of the classification are the same
All_Same_Value = result_df.apply(
    lambda row: 'yes' if len(set(row[subset_columns].replace('', float('nan')).dropna())) <= 1 else 'no',
    axis=1
)
print(result_df)
print('first',result_df.info())
# # If all values in the row are "", update 'All_Same_Value' column to 'no'
# result_df.insert(insert_position_All_Same_Value, 'All_Same_Value', All_Same_Value)
# # result_df.loc[result_df[subset_columns].eq("").all(axis=1), 'All_Same_Value'] = 'no'
########################################################################################
# insert_position = len(result_df.columns) - 4
# result_df.insert(insert_position, 'Most_frequent_value', most_frequent_values2)
Last_CI_value_by_approved_clus_percent = (last_yes_count / clus_amount_last_CI) * 100
result_df['Last_CI_value_by_approved_clus_percent'] = ''
result_df.at[0, 'Last_CI_value_by_approved_clus_percent'] = Last_CI_value_by_approved_clus_percent
print('second',result_df.info())
result_df

                                       cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                    Corn
1       00009398-6884-4F9D-AF20-9F6997D30B68                Soybeans
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                    Corn
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                  Cotton
4       0002DC5F-9F69-404F-9353-862F373844C0                Soybeans
...                                      ...                     ...
180733  55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3
180734  63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C
180735  52B817D4-793B-43CA-B432-40EF5EE8040D
180736  8929d73b-739c-451b-9b6e-fe09ee5fa725
180737  A591B261-0E75-40B6-A8A6-07E56E282CF3

       crops_acres_df_20230529 crops_acres_df_20230612  \
0
1
2
3
4
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230619 crops_acres_df_20230627  \
0
1
2
3
4
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230704 crops_acres_df_20230711  \
0                         Corn                    Corn
1
2
3                        Other                Soybeans
4                         Corn                Soybeans
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230725 crops_acres_df_20230808_v2  \
0                        Other                       Corn
1
2
3                       Cotton                     Cotton
4                     Soybeans                   Soybeans
...                        ...                        ...
180733                  Non Ag
180734                   Other                   Soybeans
180735                                           Soybeans
180736                                               Corn
180737                                           Soybeans

       crops_acres_df_20230822  CIs_value_count ALL_CIs_Match_forecast  \
0                         Corn                5                     No
1                                             0                    Yes
2                                             0                    Yes
3                       Cotton                5                     No
4                     Soybeans                5                     No
...                        ...              ...                    ...
180733                                        1                     No
180734                Soybeans                3                     No
180735                                        1                     No
180736                    Corn                2                     No
180737                                        1                     No

       Last_CI_value_Match_forecast ALL_CIs_Match_percent  \
0                               Yes             56.511082
1                                No
2                                No
3                               Yes
4                               Yes
...                             ...                   ...
180733                           No
180734                           No
180735                           No
180736                           No
180737                           No

       Last_CI_value_Match_forecast_percent
0                                 39.410639
1
2
3
4
...                                     ...
180733
180734
180735
180736
180737

[180738 rows x 16 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 180738 entries, 0 to 180737
Data columns (total 16 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   cluid                                 180738 non-null  object
 1   ProAg's AR no duplictes               180738 non-null  object
 2   crops_acres_df_20230529               180738 non-null  object
 3   crops_acres_df_20230612               180738 non-null  object
 4   crops_acres_df_20230619               180738 non-null  object
 5   crops_acres_df_20230627               180738 non-null  object
 6   crops_acres_df_20230704               180738 non-null  object
 7   crops_acres_df_20230711               180738 non-null  object
 8   crops_acres_df_20230725               180738 non-null  object
 9   crops_acres_df_20230808_v2            180738 non-null  object
 10  crops_acres_df_20230822               180738 non-null  object
 11  CIs_value_count                       180738 non-null  int64
 12  ALL_CIs_Match_forecast                180738 non-null  object
 13  Last_CI_value_Match_forecast          180738 non-null  object
 14  ALL_CIs_Match_percent                 180738 non-null  object
 15  Last_CI_value_Match_forecast_percent  180738 non-null  object
dtypes: int64(1), object(15)
memory usage: 27.5+ MB
first None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 180738 entries, 0 to 180737
Data columns (total 17 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   cluid                                   180738 non-null  object
 1   ProAg's AR no duplictes                 180738 non-null  object
 2   crops_acres_df_20230529                 180738 non-null  object
 3   crops_acres_df_20230612                 180738 non-null  object
 4   crops_acres_df_20230619                 180738 non-null  object
 5   crops_acres_df_20230627                 180738 non-null  object
 6   crops_acres_df_20230704                 180738 non-null  object
 7   crops_acres_df_20230711                 180738 non-null  object
 8   crops_acres_df_20230725                 180738 non-null  object
 9   crops_acres_df_20230808_v2              180738 non-null  object
 10  crops_acres_df_20230822                 180738 non-null  object
 11  CIs_value_count                         180738 non-null  int64
 12  ALL_CIs_Match_forecast                  180738 non-null  object
 13  Last_CI_value_Match_forecast            180738 non-null  object
 14  ALL_CIs_Match_percent                   180738 non-null  object
 15  Last_CI_value_Match_forecast_percent    180738 non-null  object
 16  Last_CI_value_by_approved_clus_percent  180738 non-null  object
dtypes: int64(1), object(16)
memory usage: 28.9+ MB
second None

,cluid,ProAg's AR no duplictes,crops_acres_df_20230529,crops_acres_df_20230612,crops_acres_df_20230619,crops_acres_df_20230627,crops_acres_df_20230704,crops_acres_df_20230711,crops_acres_df_20230725,crops_acres_df_20230808_v2,crops_acres_df_20230822,CIs_value_count,ALL_CIs_Match_forecast,Last_CI_value_Match_forecast,ALL_CIs_Match_percent,Last_CI_value_Match_forecast_percent,Last_CI_value_by_approved_clus_percent
0,000043F8-7B73-418C-8258-889DD97EDFAB,Corn,,,,,Corn,Corn,Other,Corn,Corn,5,No,Yes,56.511082,39.410639,61.612317
1,00009398-6884-4F9D-AF20-9F6997D30B68,Soybeans,,,,,,,,,,0,Yes,No,,,
2,0000dfbe-5904-48a9-9b02-c9de79dfa4de,Corn,,,,,,,,,,0,Yes,No,,,
3,00012A0C-34A8-4021-BF0B-7645FB6DF7BB,Cotton,,,,,Other,Soybeans,Cotton,Cotton,Cotton,5,No,Yes,,,
4,0002DC5F-9F69-404F-9353-862F373844C0,Soybeans,,,,,Corn,Soybeans,Soybeans,Soybeans,Soybeans,5,No,Yes,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180733,55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3,,,,,,,,Non Ag,,,1,No,No,,,
180734,63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C,,,,,,,,Other,Soybeans,Soybeans,3,No,No,,,
180735,52B817D4-793B-43CA-B432-40EF5EE8040D,,,,,,,,,Soybeans,,1,No,No,,,
180736,8929d73b-739c-451b-9b6e-fe09ee5fa725,,,,,,,,,Corn,Corn,2,No,No,,,
180737,A591B261-0E75-40B6-A8A6-07E56E282CF3,,,,,,,,,Soybeans,,1,No,No,,,

In [96]:
# add ml_model to df
last_csv_file = csv_files[-1]
file_path = os.path.join(folder_path, last_csv_file)
last_csv_file_df = pd.read_csv(file_path)
ml_model_size_mapping = dict(zip(last_csv_file_df["clu_id"], last_csv_file_df['ml_model_code']))
result_df["last_ml_model"] = result_df["cluid"].map(ml_model_size_mapping)

# dataframe of all values that were calculated before
values_for_calc = {'Number of clus that match forecast in all CIs': all_yes_count, 'Number of clus that match forecast in latest CI': last_yes_count,
                   'number of clu approved latest CI': clus_amount_last_CI, 'Total clu number': result_df.shape[0]}

values_for_calc_df = pd.DataFrame(list(values_for_calc.items()), columns=['Variable', 'Value']).reset_index(drop=True)
print(values_for_calc_df)
final_df = pd.concat([result_df, values_for_calc_df], axis=1)

# Create a new DataFrame to store the sums of matching values to forecast for each column (CI)
sums_df = pd.DataFrame(columns=['Column', 'Sum'])
print('df',df)
print('final', final_df)
# Iterate through each column
# for col_name in final_df.columns[2:10]:
#     matching_sum = df.loc[df[col_name] == df.columns[1], col_name].sum()
#     sums_df = sums_df.append({'Column': col_name, 'Sum': matching_sum}, ignore_index=True)

                                          Variable   Value
0    Number of clus that match forecast in all CIs  102137
1  Number of clus that match forecast in latest CI   71230
2                 number of clu approved latest CI  115610
3                                 Total clu number  180738
df                                        cluid crop_code ml_model
0       94BE7D75-5628-49A8-8ED6-F44B3BB20C0A        81      Y8a
1       75CCFEEC-FAB8-4FF1-A970-1399D38A5684        41       fa
2       A1596150-F2BA-437B-8C38-BAB392013FD7        41      Y9a
3       0BC01A27-AC8B-4335-8340-9F9A012FF4EF        81       B8
4       E7D7D229-E961-47AE-9E98-90213AC19D98        41      Y9a
...                                      ...       ...      ...
115605  37788F5F-8A25-4C5A-97D3-DE1895D36CD1        81       B8
115606  6F7A3E71-17B0-4D49-910F-3398286568CD        41      Y9a
115607  7ACE9A78-A90F-4C35-A610-34D390CC411C        41       B8
115608  54507aa1-1bbf-45c0-b5d6-78426115a89d        21      Y9a
115609  5791C8FF-2E31-4C15-941A-465B781909BC        41      Y8a

[115610 rows x 3 columns]
final                                        cluid ProAg's AR no duplictes  \
0       000043F8-7B73-418C-8258-889DD97EDFAB                    Corn
1       00009398-6884-4F9D-AF20-9F6997D30B68                Soybeans
2       0000dfbe-5904-48a9-9b02-c9de79dfa4de                    Corn
3       00012A0C-34A8-4021-BF0B-7645FB6DF7BB                  Cotton
4       0002DC5F-9F69-404F-9353-862F373844C0                Soybeans
...                                      ...                     ...
180733  55D2CE5E-38AE-457D-A69F-B4A80C6DB2A3
180734  63D75BCA-0F6D-4C2D-9E01-2C58BC254F3C
180735  52B817D4-793B-43CA-B432-40EF5EE8040D
180736  8929d73b-739c-451b-9b6e-fe09ee5fa725
180737  A591B261-0E75-40B6-A8A6-07E56E282CF3

       crops_acres_df_20230529 crops_acres_df_20230612  \
0
1
2
3
4
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230619 crops_acres_df_20230627  \
0
1
2
3
4
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230704 crops_acres_df_20230711  \
0                         Corn                    Corn
1
2
3                        Other                Soybeans
4                         Corn                Soybeans
...                        ...                     ...
180733
180734
180735
180736
180737

       crops_acres_df_20230725 crops_acres_df_20230808_v2  \
0                        Other                       Corn
1
2
3                       Cotton                     Cotton
4                     Soybeans                   Soybeans
...                        ...                        ...
180733                  Non Ag
180734                   Other                   Soybeans
180735                                           Soybeans
180736                                               Corn
180737                                           Soybeans

       crops_acres_df_20230822  CIs_value_count ALL_CIs_Match_forecast  \
0                         Corn                5                     No
1                                             0                    Yes
2                                             0                    Yes
3                       Cotton                5                     No
4                     Soybeans                5                     No
...                        ...              ...                    ...
180733                                        1                     No
180734                Soybeans                3                     No
180735                                        1                     No
180736                    Corn                2                     No
180737                                        1                     No

       Last_CI_value_Match_forecast ALL_CIs_Match_percent  \
0                               Yes             56.511082
1                                No
2                                No
3                               Yes
4                               Yes
...                             ...                   ...
180733                           No
180734                           No
180735                           No
180736                           No
180737                           No

       Last_CI_value_Match_forecast_percent  \
0                                 39.410639
1
2
3
4
...                                     ...
180733
180734
180735
180736
180737

       Last_CI_value_by_approved_clus_percent last_ml_model  \
0                                   61.612317           Y8a
1                                                       NaN
2                                                       NaN
3                                                       Y9a
4                                                        B8
...                                       ...           ...
180733                                                  NaN
180734                                                   B8
180735                                                  NaN
180736                                                   B8
180737                                                  NaN

                                               Variable     Value
0         Number of clus that match forecast in all CIs  102137.0
1       Number of clus that match forecast in latest CI   71230.0
2                      number of clu approved latest CI  115610.0
3                                      Total clu number  180738.0
4                                                   NaN       NaN
...                                                 ...       ...
180733                                              NaN       NaN
180734                                              NaN       NaN
180735                                              NaN       NaN
180736                                              NaN       NaN
180737                                              NaN       NaN

[180738 rows x 20 columns]

In [98]:
# # Export the DataFrame to a CSV file
final_df1 = pd.concat([final_df, models_df],axis=1)

final_df1.info()
df_filtered = final_df1[final_df1['CIs_value_count'] != 0]
output_file = r"C:\Users\User\Documents\ProAg_2023_CC\ProAg_2023_InSeason\proag_season2023_final_with_forecast_report.csv"
df_filtered.to_csv(output_file, index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180738 entries, 0 to 180737
Data columns (total 31 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   cluid                                   180738 non-null  object
 1   ProAg's AR no duplictes                 180738 non-null  object
 2   crops_acres_df_20230529                 180738 non-null  object
 3   crops_acres_df_20230612                 180738 non-null  object
 4   crops_acres_df_20230619                 180738 non-null  object
 5   crops_acres_df_20230627                 180738 non-null  object
 6   crops_acres_df_20230704                 180738 non-null  object
 7   crops_acres_df_20230711                 180738 non-null  object
 8   crops_acres_df_20230725                 180738 non-null  object
 9   crops_acres_df_20230808_v2              180738 non-null  object
 10  crops_acres_df_20230822                 180738 non-null  object
 11  CIs_value_count                         180738 non-null  int64
 12  ALL_CIs_Match_forecast                  180738 non-null  object
 13  Last_CI_value_Match_forecast            180738 non-null  object
 14  ALL_CIs_Match_percent                   180738 non-null  object
 15  Last_CI_value_Match_forecast_percent    180738 non-null  object
 16  Last_CI_value_by_approved_clus_percent  180738 non-null  object
 17  last_ml_model                           115610 non-null  object
 18  Variable                                4 non-null       object
 19  Value                                   4 non-null       float64
 20  cluid                                   180738 non-null  object
 21  ProAg's AR no duplictes                 154404 non-null  object
 22  crops_acres_df_20230529                 1241 non-null    object
 23  crops_acres_df_20230612                 6326 non-null    object
 24  crops_acres_df_20230619                 12463 non-null   object
 25  crops_acres_df_20230627                 22351 non-null   object
 26  crops_acres_df_20230704                 113456 non-null  object
 27  crops_acres_df_20230711                 115606 non-null  object
 28  crops_acres_df_20230725                 115608 non-null  object
 29  crops_acres_df_20230808_v2              115612 non-null  object
 30  crops_acres_df_20230822                 115610 non-null  object
dtypes: float64(1), int64(1), object(29)
memory usage: 44.1+ MB